//vite.config.js

/*# WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
# JANGAN LUPA FOLLOW IG : @jopra_
# BY JOKO PRAMONO RAMADHANI

# WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
# JANGAN LUPA FOLLOW IG : @jopra_
# BY JOKO PRAMONO RAMADHANI

# WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
# JANGAN LUPA FOLLOW IG : @jopra_
# BY JOKO PRAMONO RAMADHANI

# WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
# JANGAN LUPA FOLLOW IG : @jopra_
# BY JOKO PRAMONO RAMADHANI8 */


import { defineConfig } from 'vite'  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI

//# WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI


export default defineConfig({  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI

 // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI

  
  server: {  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
     // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
    port: 5173,  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
     // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
  },  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
   // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
  build: {  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
     // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
    outDir: 'dist',  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
     // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
    sourcemap: true  // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
     // # WAKACIPUK - KECIPAK KECIPUK PANTAI ANYER
//# JANGAN LUPA FOLLOW IG : @jopra_
//# BY JOKO PRAMONO RAMADHANI
  }
})
